# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDVkZTU2ZGI2MzA2MzVhMTg2NzBmMTY5ODEyZDcwZTVmZjlhMjkyZTdlYzk0ZGI3ODQ1NDRkNzdjNDg1NWM2NzBjZDUxNDE3MjJhOTkwNGRmOGMyYWMxYzk4MzZlMzkxNjVhNzEwNjczZDUzM2NhYTg1ZTNmYWZmYzVkOGJlMzY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
