@echo off
echo Deleting Kubernetes...
if exist kubernetes rmdir /s /q kubernetes
echo Deleting docker-compose...
if exist docker-compose rmdir /s /q docker-compose
echo Deleting node_modules...
if exist node_modules rmdir /s /q node_modules
echo Deleting package.json...
if exist package.json del package.json
if exist package-lock.json del package-lock.json
echo Deleting .yo-repository...
if exist .yo-repository rmdir /s /q .yo-repository
if exist .yo-rc.json del .yo-rc.json
echo Deleting .jhipster...
if exist .jhipster rmdir /s /q .jhipster
echo Deleting target...
if exist target rmdir /s /q target
echo Deleting .npmrc...
if exist .npmrc del .npmrc
echo Deleting Gateway...
if exist psqlgateway rmdir /s /q psqlgateway
call saathratri-cleanup-dev-sql.bat
