@echo off
echo Cleaning up previous code...
call cleanup.bat
echo Generating code...
call jhipster --blueprints ai-postgresql jdl non-reactive-mf.jdl --monorepository --workspaces --skip-jhipster-dependencies --skip-git
