#!/usr/bin/env bash
# =============================================================================
# saathratri-run-all-tests.sh — reliable one-shot full test run for the ai-postgresql example
#
# Three (non-reactive) JHipster apps generated by generator-jhipster-ai-postgresql
# from non-reactive-mf.jdl:
#   psqlgateway (gateway, :8080, microfrontend shell; entities Blog,Post,Tag,TajUser)
#   psqlblog    (microservice remote, :8081; Blog,Post,Tag[+pgvector],TajUser)
#   psqlstore   (microservice remote, :8082; Product,Report)
#
# Runs, in order, for all 3 apps:
#   1. (optional) regen from the blueprint              --regen   (in-place, --force)
#   2. npm install (workspaces) when node_modules is missing
#   3. backend unit + integration (mvnw verify; PostgreSQL/pgvector Testcontainers)
#   4. frontend (vitest, ng test)
#   5. webapp build into target/classes/static          (required for e2e index.html)
#   6. bring up the dev docker stack (Keycloak + Registry + 3x Postgres)
#   7. launch the 3 backends once, wait for a REAL readiness gate
#   8. e2e (Cypress) per app, judged by EXIT CODE (no retry)
#   9. tear down the 3 backends (Docker stack left running)
#
# Reliability notes (shared with the cassandra example's harness):
#   - Free 8080/8081/8082 and BLOCK until clear before every backend launch; a backend started
#     over a straggler dies "Port 80xx already in use" and e2e then hits a dead :8080
#     ("No request ever occurred"). See wait_ports_free.
#   - e2e:headless chains a Windows-broken ci:server:await; we call `npm run e2e:cypress`.
#   - e2e pass/fail = cypress EXIT CODE, never a log grep.
#
# ai-postgresql specifics:
#   - regen here is IN-PLACE via a direct `jhipster ... --force` (the example's
#     saathratri-generate-code-dev-sql-mf.sh delegates to a missing cleanup.sh and would fail).
#   - infra ports needed: 5432 (postgres), 9080 (keycloak), 8761 (registry) — stop any other
#     example's docker stack first (e.g. the cassandra one).
#   - Tag carries pgvector columns; the test PostgreSQL Testcontainer uses pgvector/pgvector
#     (handled in the blueprint), so backend ITs need a running Docker daemon.
#
# Usage:
#   sh saathratri-run-all-tests.sh                 # full run, no regen (apps already generated)
#   sh saathratri-run-all-tests.sh --regen         # in-place regen + npm install + full run
#   sh saathratri-run-all-tests.sh --skip-backend --skip-frontend   # e2e only
#   sh saathratri-run-all-tests.sh --no-e2e        # backend + frontend only
#   sh saathratri-run-all-tests.sh --headless      # run Cypress headless (default is headed/visible)
#
# Requires: Docker daemon running, JDK 21, Node 22+, blueprint npm-linked (for --regen).
# =============================================================================
set -u

APPS="psqlgateway psqlblog psqlstore"
declare -A PORT=( [psqlgateway]=8080 [psqlblog]=8081 [psqlstore]=8082 )
declare -A PROBE=( [psqlblog]="services/psqlblog/api/blogs" [psqlstore]="services/psqlstore/api/products" )

export NODE_OPTIONS=--use-system-ca
export MAVEN_OPTS="-Djavax.net.ssl.trustStoreType=Windows-ROOT"

ROOT="$(cd "$(dirname "$0")" && pwd)"
LOG="$ROOT/.test-logs"; mkdir -p "$LOG"
cd "$ROOT"

REGEN=0; SKIP_BE=0; SKIP_FE=0; DO_E2E=1; HEADED=1
for a in "$@"; do case "$a" in
  --regen) REGEN=1;; --skip-backend) SKIP_BE=1;; --skip-frontend) SKIP_FE=1;;
  --no-e2e) DO_E2E=0;; --headless) HEADED=0;; *) echo "unknown arg: $a"; exit 2;; esac; done
# Headed by default so the Cypress interactions are visible (`cypress run` alone is
# headless, and Chrome's new-headless mode just shows a blank white window on Windows).
E2E_ARGS=""; [ "$HEADED" = 1 ] && E2E_ARGS="-- --headed"

declare -A R_BE_UNIT R_BE_IT R_FE R_E2E
FAIL=0
hr(){ printf '%.0s─' $(seq 1 70); echo; }
say(){ echo; hr; echo ">>> $*"; hr; }

kill_backends() {
  powershell.exe -NoProfile -Command "
    Get-CimInstance Win32_Process -Filter \"Name='java.exe'\" |
      Where-Object { \$_.CommandLine -match 'jhipster-ai-postgresql-example' -or \$_.CommandLine -match 'Psql(gateway|blog|store)App' } |
      ForEach-Object { try { Stop-Process -Id \$_.ProcessId -Force -ErrorAction Stop } catch {} }
    foreach (\$p in 8080,8081,8082) {
      Get-NetTCPConnection -State Listen -LocalPort \$p -ErrorAction SilentlyContinue |
        ForEach-Object { try { Stop-Process -Id \$_.OwningProcess -Force -ErrorAction Stop } catch {} }
    }" >/dev/null 2>&1 || true
}

wait_ports_free() {
  for i in $(seq 1 30); do
    busy=$(powershell.exe -NoProfile -Command "(Get-NetTCPConnection -State Listen -LocalPort 8080,8081,8082 -ErrorAction SilentlyContinue | Measure-Object).Count" 2>/dev/null | tr -dc '0-9')
    [ "${busy:-0}" = "0" ] && return 0
    sleep 2
  done
  echo "  ⚠ ports still busy after wait: ${busy:-?} listener(s)"; return 1
}

http(){ curl -s -o /dev/null -w '%{http_code}' --max-time 6 "$1" 2>/dev/null; }

ensure_npm() {
  for app in $APPS; do
    if [ ! -d "$app/node_modules" ] && [ ! -d "node_modules/.bin" ]; then
      say "npm install (workspaces) — node_modules missing"
      npm install > "$LOG/npm-install.log" 2>&1 || { echo "  ✖ npm install FAILED (see $LOG/npm-install.log)"; FAIL=1; }
      return
    fi
  done
}

# ---- 0. clean slate -------------------------------------------------------
say "Clean slate: stopping any running example backends + freeing ports"
kill_backends
wait_ports_free || { echo "  could not free 8080/8081/8082 — aborting"; exit 1; }
echo "  ports 8080/8081/8082 free"

# ---- 1. regen (optional, in-place) ----------------------------------------
if [ "$REGEN" = 1 ]; then
  say "Regenerating from blueprint (ai-postgresql, non-reactive-mf.jdl, in-place --force)"
  jhipster --blueprints ai-postgresql jdl non-reactive-mf.jdl \
    --monorepository --workspaces --skip-jhipster-dependencies --force > "$LOG/regen.log" 2>&1
  if ! grep -qa "execution is complete" "$LOG/regen.log"; then
    echo "REGEN FAILED — see $LOG/regen.log"; tail -15 "$LOG/regen.log"; exit 1
  fi
  echo "regen OK"
fi

# ---- 2. npm install if needed --------------------------------------------
if [ "$SKIP_FE" = 0 ] || [ "$DO_E2E" = 1 ]; then ensure_npm; fi

# ---- 3. backend unit + IT -------------------------------------------------
if [ "$SKIP_BE" = 0 ]; then
  for app in psqlstore psqlblog psqlgateway; do
    say "Backend (unit + IT): $app"
    ( cd "$app" && ./mvnw -ntp -Dskip.npm clean verify ) > "$LOG/be-$app.log" 2>&1
    ok=$?
    mapfile -t totals < <(grep -aE "^\[INFO\] Tests run: [0-9]+, Failures: [0-9]+, Errors: [0-9]+, Skipped: [0-9]+$" "$LOG/be-$app.log")
    R_BE_UNIT[$app]="${totals[0]:-(none)}"
    R_BE_IT[$app]="${totals[1]:-(none)}"
    if [ $ok -ne 0 ] || ! grep -qa "BUILD SUCCESS" "$LOG/be-$app.log"; then
      echo "  ✖ $app backend FAILED (see $LOG/be-$app.log)"; FAIL=1
    else echo "  ✔ $app backend OK"; fi
  done
fi

# ---- 4. frontend (vitest) -------------------------------------------------
if [ "$SKIP_FE" = 0 ]; then
  for app in $APPS; do
    say "Frontend (vitest): $app"
    ( cd "$app" && npx ng test --watch=false ) > "$LOG/fe-$app.log" 2>&1
    ok=$?
    R_FE[$app]="$(sed -E 's/\x1b\[[0-9;]*m//g' "$LOG/fe-$app.log" | grep -aE 'Tests +[0-9]+ (passed|failed)' | tail -1 | sed 's/^[[:space:]]*//')"
    if [ $ok -ne 0 ]; then echo "  ✖ $app frontend FAILED (see $LOG/fe-$app.log)"; FAIL=1
    else echo "  ✔ $app frontend OK"; fi
  done
fi

# ---- 5-8. e2e -------------------------------------------------------------
if [ "$DO_E2E" = 1 ]; then
  say "Building webapps into target/classes/static (required for e2e)"
  for app in $APPS; do
    ( cd "$app" && npm run webapp:build ) > "$LOG/web-$app.log" 2>&1 || { echo "  ✖ $app webapp build FAILED"; FAIL=1; }
    [ -f "$app/target/classes/static/index.html" ] && echo "  ✔ $app index.html" || { echo "  ✖ $app index.html MISSING"; FAIL=1; }
  done

  say "Bringing up dev docker stack (Keycloak + Postgres x3 first; Registry after Keycloak is ready)"
  # Order matters: the JHipster Registry is an OAuth2 client that does eager OIDC discovery against
  # http://keycloak:9080/realms/jhipster/.well-known/openid-configuration at boot. If Keycloak isn't
  # serving yet the registry context fails fast and the container exits(1) — then no app can register
  # with Eureka, the gateway gets no routes to the remotes, and every entity e2e 404s. So bring up
  # Keycloak + the databases, GATE on Keycloak's OIDC endpoint, and only THEN start the registry.
  ( cd psqlgateway && docker compose -f src/main/docker/keycloak.yml up -d ) > "$LOG/docker-keycloak.log" 2>&1 || { echo "  ✖ keycloak up failed"; FAIL=1; }
  for app in $APPS; do
    ( cd "$app" && npm run docker:db:up ) > "$LOG/docker-db-$app.log" 2>&1 || { echo "  ✖ $app postgres up failed"; FAIL=1; }
  done

  printf "  waiting Keycloak OIDC (:9080) "
  oidc="http://localhost:9080/realms/jhipster/.well-known/openid-configuration"
  for i in $(seq 1 60); do [ "$(http "$oidc")" = 200 ] && break; sleep 3; printf '.'; done
  kc=$(http "$oidc"); echo " $kc"
  [ "$kc" = 200 ] || { echo "  ✖ Keycloak never served OIDC discovery — registry would crash; aborting e2e"; FAIL=1; }

  ( cd psqlgateway && docker compose -f src/main/docker/jhipster-registry.yml up -d ) > "$LOG/docker-registry.log" 2>&1 || { echo "  ✖ registry up failed"; FAIL=1; }
  printf "  waiting JHipster Registry (:8761) "
  for i in $(seq 1 60); do c=$(http http://localhost:8761/management/health); case "$c" in 200|401) break;; esac; sleep 3; printf '.'; done
  rg=$(http http://localhost:8761/management/health); echo " $rg"
  case "$rg" in 200|401) ;; *) echo "  ✖ Registry not live on :8761 (got $rg) — remotes can't register; aborting e2e"; FAIL=1;; esac

  say "Ensuring ports free before launching backends"
  kill_backends; wait_ports_free || { echo "  ports busy — aborting e2e"; FAIL=1; }

  # Deterministic fake embedding model: lets the embedding-lifecycle e2e prove
  # create/update embedding generation offline (no OPENAI_API_KEY, no API cost).
  # CYPRESS_fakeEmbeddings tells the specs the backend has it enabled.
  export OPENAI_EMBEDDING_FAKE=true
  export CYPRESS_fakeEmbeddings=true

  say "Launching 3 backends (single job)"
  ( cd psqlgateway && ./mvnw -ntp -Dskip.npm spring-boot:run -Dspring-boot.run.profiles=dev > "$LOG/run-psqlgateway.log" 2>&1 ) &
  ( cd psqlblog    && ./mvnw -ntp -Dskip.npm spring-boot:run -Dspring-boot.run.profiles=dev > "$LOG/run-psqlblog.log"    2>&1 ) &
  ( cd psqlstore   && ./mvnw -ntp -Dskip.npm spring-boot:run -Dspring-boot.run.profiles=dev > "$LOG/run-psqlstore.log"   2>&1 ) &

  say "Readiness gate: app health (808x) + gateway->remote routes"
  for app in $APPS; do
    p=${PORT[$app]}
    printf "  waiting %s health :%s " "$app" "$p"
    for i in $(seq 1 72); do [ "$(http http://localhost:$p/management/health)" = 200 ] && break; sleep 5; printf '.'; done
    code=$(http http://localhost:$p/management/health)
    echo " $code"; [ "$code" = 200 ] || { echo "  ✖ $app never became healthy"; FAIL=1; }
  done
  printf "  gateway root (index.html): "; echo "$(http http://localhost:8080/)"
  for app in psqlblog psqlstore; do
    probe="http://localhost:8080/${PROBE[$app]}"
    printf "  waiting gateway->%s route " "$app"
    for i in $(seq 1 60); do c=$(http "$probe"); case "$c" in 200|301|302|401) break;; esac; sleep 5; printf '.'; done
    c=$(http "$probe"); echo " $c"
    case "$c" in 200|301|302|401) ;; *) echo "  ✖ gateway->$app route not live ($c)"; FAIL=1;; esac
  done
  echo "  letting federation settle 20s"; sleep 20

  for app in $APPS; do
    say "E2E (Cypress): $app"
    ( cd "$app" && npm run e2e:cypress $E2E_ARGS ) > "$LOG/e2e-$app.log" 2>&1
    rc=$?
    summary="$(grep -aE 'All specs passed|[0-9]+ of [0-9]+ failed' "$LOG/e2e-$app.log" | tr -d '\033' | sed -E 's/\x1b\[[0-9;]*m//g; s/^[[:space:]]*//' | tail -1)"
    if [ $rc -eq 0 ]; then
      R_E2E[$app]="PASS — ${summary:-(no summary line)}"
      echo "  ✔ $app e2e passed"
    else
      R_E2E[$app]="FAIL(rc=$rc) — ${summary:-(no cypress summary; see log)}"
      echo "  ✖ $app e2e FAILED (rc=$rc, see $LOG/e2e-$app.log)"; FAIL=1
    fi
  done

  say "Tearing down backends (Docker stack left running)"
  kill_backends
fi

# ---- report ---------------------------------------------------------------
say "REPORT"
printf "%-14s | %-34s | %-34s | %-26s | %s\n" "APP" "BACKEND unit" "BACKEND IT" "FRONTEND" "E2E"
for app in $APPS; do
  printf "%-14s | %-34s | %-34s | %-26s | %s\n" "$app" \
    "${R_BE_UNIT[$app]:-skipped}" "${R_BE_IT[$app]:-skipped}" "${R_FE[$app]:-skipped}" "${R_E2E[$app]:-skipped}"
done
echo
if [ "$FAIL" = 0 ]; then echo "✅ ALL GREEN"; else echo "❌ FAILURES — inspect $LOG/*.log"; fi
echo "logs: $LOG"
exit $FAIL
