# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjZhYzMzYWViY2UyYmI5Y2VjNWQ0MzViMTdjNzYyMWUxN2FjOGM5NDJkZWRiMmU1OWU0OTM4NWJiODU3MWQ2YjA2NTE2ODkwMzdkMzc0NjRjMDZiYTc3OTE1N2RjYmJkY2I3MTgxNTYxZDEzZDVmYzM1M2U1MGE4MDM4NmY1NDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
