# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Mjc2YjZhNDNmNGQyZDE2MjE2MGM0ZDJkMGY2YjlmNWVjN2QwMzA3ZDBkZDZiZjNkOTk4ODQ1YTZkNmY1MjhjYzY0MGNkYTNhNzM3OTg2NjViYzE4MWI5MWFhNTRmOGJkZjE0MjQxYWRmYjY3MTU1ODljMTk2ODNlNjgwNGViNjA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
