# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MGNhMjdjZWJjOWVjZmU1NDEzODRhZDQ1M2RlY2VlNWZmZWRkNDQ4MGE1NTZhM2FlYmI0NTQ3M2M1NTljOGY4NTVkYWQ1NDkzMDQ2NjNiOGU0N2Y0OGU0M2Q0ZDMzZWU5MGMzNmY5YWUzNmQ0Yjk5OWE0NGU2M2I1Yjg3ZDY4MDQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
