# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Y2YyNDI1MTdlNmQxYTcxZjc4N2RiYzNiMWI4NTMzZGQwODVjOWI0MjliNDlkNzM5OWNhM2JiZWI1Yjk5MjAxNDdlNTQ3ZDAzYzRlNjg1ZTQwZGQyZGQxYTI0MDc4M2Y2YmY3OGUyNTJkODk4YWU1OTYyNjU1ZWQyNWEzYzU4ZTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
