# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDBjNTg0NjViNmZmMDYwNjQ4MTE1MzgxMTQ3NzVkODA0ZDAwOGY3ODQ3YTlhZTFjZTVjMThiY2FmMzAzNGU3OTMyNDEyOWM1MDlhN2FjM2VlMDNlNDAxYTg0MmU5ZWFhNGI1NGFiYjdlNDk3MDQ3NWU3ZjI5NzEzZTBiYzAxNDQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
