# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWE2ZmI1ODViNzMxNGZhMmE1NzJkODRkNTUzNWJhMzAyODIxZDVkN2FkZTlhODA1ZmZlN2UzYjEyZWE1MjkyM2I0ZGExYmVlOTRmOWI1OGVhYjcyNzZjZjAwMDRkYWU4ZDYxYWIwOTgyMjlhZmNkNGEzZGIyYzgwMzE5NmQ3YmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
