# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmEyNzU2YzNkYjQzMjExOTYxMjQwYmNmN2I0YjczNGFhZDUyYzI3MGU4NTM1NDBkOTNkYmNkYTA3ZDYwYTdmODI4YThjNDEzYWY3MGM1MTllYTc4NWI1NzY5Yjk4YzkyZGM5NGFjODM4Yzg2OTVjMzMyMTgxMTZiZTM0YTc5YWM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
