# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTNkZjFiNzg5YjUxMjA2OGIzZTY5YjI2YzZkNWM4ZTRmNWY5ZWZiYzZkODVlY2Q2ZGQwZGIxZjM4NzJlNTE1ODFiYWVjMzAxMTIwOTBhODA4NGI1NWNkZTg2ZDc5YTZmY2E0MDdmZDVkZTkyNjMwOGM0NzM4ZWY2ODY2YzdmMjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
