# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDU3ZWUzZjFkODg1YTc1ZDhhMGRkMGRiOTg3NDViYjA5YjQ0ODA3NTAwZTE3N2VmY2JiMzBhMDlkMDkwMDkzZDI4Y2YzMmZlN2JhNGQyNDIxZGY2N2QxZTdiZDAwNTc5YzgyZGRhNzdjM2FkYzJmZjFiODhhYjQ3NjNhN2UyZDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
