# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Njg0ZDllNGE1NDYxOGZjZTY3MWJjYmFmNzcxNTBjNTI0NmUwZTQ5MTM2N2Q3NDU1MDdlMmYyNGFlMDY0NzdiMGIyMWIyMmYzOTk5OTUwNGVlNWM5MmZiOGNmMDQyNjNmYWYxODYwODQ4MTM4MDFiNmJlM2UxMjkyMGNjMmMwZDU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
