# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzFiOWM5YzZlNDVlOWRkZWY4YWI0NWY1YzA5OTgzZDVmNzI5MDI3YTFkYmMzN2YzYjljYzYyNmM1ZWRlN2I4MGQ4YTBmODI5MGM0M2I1ZDQ2Mzk3MTc0Y2Q4OGExMDljMzRhZmE2MzFhMTM1YTRmYTVjOTM2NTJlNTZmYzI2ODc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
