# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjY2OWQyMThiZTU5YTQ4ZGVlNzRiOTExOWNiNjJkYThjZWZkM2RlZWJjMDFiY2Y3N2YwNjQxZWQ2ZDljYmUzMDIxYThkNDJmYzY5YzU3ZDAxZGVlYmNhMDI1Y2U4OGU5ZmRhZDY1MzkyMmI1YzE1YWE0ZTJhYmVjNWI4NzBmZmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
