# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjVhNWM0YjQ5ODk2MjZkODMxMDZiOGVlNDA3MjA1YzE5NDU4YzY3MzgwYmRkZWE5Yjc5NGZlMDhiYThiZmRkNmViMjNkZWMyNTQyZDA2Mzc4Y2JlNzU4MGVhMjMwYTA4ZDE3ZTYzNDlmMjc4MjhjNjc4MmUwNTg2YzkxMzFmNzY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
