# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NGZhYzM3ZDc4NTMyMjc3YTJiODE2MDkyMDkyNjQwODUyODlkYzhhYTEyN2YzNjM5MjAyZGJlMDQzNjExNDg3NTlhYjQ4ZjdlYTFkMGRiZWJmOTIwOTQ0MTljZjVhNzk1ODc4NWNmN2FhMGM3YTQ0NWRjYWNlNTkzYTAxMmFmMGI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
