# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MzQyMTEwMjBlMGRkMmMwYzgxYjAxMmIxN2U3Mzg0MGNkMjczNGVhZjM0ODg0YjY2M2YwYzU5YzUxNTBkNzI4ZWZlYmNiZmU0NzVjNjAxMzZjYjUxNzdiMDQ5YzUzNDA3NjNmNzI4Y2NiZDhlNmI0YmNjZmY0ZjE0YmM5MThmYjg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
