#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YTBhMjM4YWJkYWQ2Y2ZjZGQ0YTc4MTRmZTMxNDhmZWQwNzdlMzczM2FkYTM2ZjhhYTRhYmFjZDYzYWQ2MzY0MjAwMjE2NjM0ZjYzZDRjZDg3NWU4YjU0NTQ5YWQwYmViNTdmNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
