#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MjkwNzY5N2MwMGYxNzg4YTNhMzIyNjAwMmY3Y2IwZjljZWE3YTI1MzE3NzE1M2RhMGFjODYyM2NiNjIzMmNhMTE2YmE0MzJmZDIxODhkM2NiNGYwNTA1YWRmNGZhMzE2YmZiMg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
