#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzMwMTcyYTIzNTQwZjE1ODgyMDUwZmZkN2ExYTVjMDgzMDg1ZjkzOWRkNjdkMjdkMWQ0ZWQ3ZTVkNjU0MTUzYzM0OGNkOTkwNjNkZjk5YjFhZjQyMjFhYmMwY2I3ZDJiNTU4YQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
