#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZWMyMWZjNGMwZDE3ZGEwZDdjZWE3NjdiZDAzZWIzZDkyYjQ5Mzc1MjNiOTQ2NWUyY2I1Yzk1MmU0ZGZiNjIyMjcwMzM5YmVhM2Y0NWRjZjAzNmZhYWVmOWU2YjNiY2JmNWI1Mw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
