#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzJiNjgxNDI3ODgwZDM2YWE4OTMxZGJmZTQ3YmY2MzJmMTY4YTFlNDVkYjg5MTg2ZTg1MDQyNzU2ZjAzMzJkY2RjN2IxZDFiYjUwZThlMWI2M2FmNmU1NTE1YzMyOTgwZDQyNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
