#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTdkNGFkMjNhOTJiZDc2MzVlYWZkNzA4ZmZkYmFlNmQ4M2Y4NDhhZmMwYTMwMjAxMGM3M2RiMjU5NzZjMGQ4Yjg5OGZiM2QxZjEyMGRiZjk4MTkwY2FkMzY0NTliZTg5MzljNw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
