#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NmViMjhlMmE0YjE0NzE3Y2NlMjEyY2Q3N2U2Mzg2YTM2MTcxY2RlZTUwMzg3ZDljYmM3ZTZkMTJiNTA1ZTMzZjc0NWZiYTkxNmY5ODg5OTgxMDY1ODk2Mzk1Y2QzZmRjNWQ3ZA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
