#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Y2UyMDYxOTRhNWQwMDRiZDBkYjgxNGMwOTFmMjYwZmFhNDZlZWUxNTIxMGM0MmQ3MDFhM2FmMmM5NmZlZTU5YTk1YzhmMmQ1YmJiMDI3ZWU5OGEyZWQ1ZGVhNjk4NDk4N2ZhOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
