#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OWU5ZWJmNzJhYzVkZjgwOWE3MmJmODc4MTViZGIwMjljMzZjMzNmMDkxNjdiZTFkMDk0ZjJhOTIxZDE0OTBhNzRkZDhkNjUwNDNlYTJlZDg4MzdiYTkxYjlhYzNlMTk1NWNlZg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
