#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YTBhOThlNTYyMTMzMjgwYjk2NjhmNmFmNmM0MzlkMzYxMzZjMTc3ODk3ODUzNzY0ZDE2NTZlZGE1ZjljYzU0NTU1MjczOWIyZmU3YzA1ODcwNWQ1NmIzMGY5ODhkYTE5Mjc5OQ==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
