#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZTA5MmEyYjU4MjUwZDg0MDExNWMyMWIxMDU0Mzk5ZTNkYjZlYzViMWEyYTU5MTgxNjcyNmIwNzlkODYzNTU2Y2JkNWEwZDFhM2E3MTJjODZkNTg3M2NhOWVmNDdmM2I3NmQxOA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
