#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NTIzYTJhNDk1NjRlOWU5ZTAxNzA2MTcwMWM3MGMzN2VmMzEyOTg0YzE3OWViZDc5ZmRiNTk5NDM2NWRhYWMyMzUzMzc2YTRhYTIyNjk5NmU4NDRlM2NjYWU1MDViZmU0NmE3Nw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
