#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDAxY2QyYzc2OTcxYzVkNWFlYWJkNmUwY2QxYjYxNjEyY2IwZTJmODVhMmExNWQ0M2UxYjU2ODQxY2Q4NDA5NjY2MjNmM2Q5NDE2ZjEzNzg4YjA4MTkyNjc1YzI2MGE0NWRmNg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
