#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Y2UyOWYwYzcxNThjZWIxOWI1ZmVkNTVmMmJjNzM5MjhjM2QwNmUxM2UxMjM4YjViNTc0MTY5YWE1MjEzYTAwOWNiMDQ5MzQwZGY4MmNkNzBkZjI1MmU1NjQ1MzJiNzI3NmE3Mg==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
