# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmY5ODc2ODZjZDhlM2UyZDhlYTRkMDIwYmVkZjIwODYyNmVlNzZmMzg3NzNjNmJkZDcxZDk5ZGQ2YWIyZTI5YTVhZmFiNzIyZTFjM2VkZmQ5MmUwNDVmNzdiMDA2MjJmYzY5ODUwYTNhZDJlYzEyNzViMzY4NDllNDk4YjUyOTI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
