# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjZkZmZjMjM0NTY0ZWE2MjA1MjdhMDdmMjIzNDczNmI4NzljYzIxZDRkNjc2NzVhYTMzZTdlMDdmOTQ3Njg4MzNiNGViOWJhMGFhZTI5ZGI4MTlkNWI4ZDRhNTlhMDViYzA0MzI3ZmNiNGJlMWZkOWNkZGUwZjgxYzEzODA0MWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
