# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmMwNDEzZTE4OWRkOTRhNGRmN2IzODY1OTdiYTIwMmM0MzNiODFmNmQ0MjBmM2Q2MDBlMzllMzRkNWZjNmM1ZTA1M2U3Mzk1YzU3YjA2MjdmOWFmMjA1YzIzN2Q4M2FkMTBkZTgyZmRhMWFjZTUzNDA4ZTJkMTUzMmI0MzlmMTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
