# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTUxMWJjZGFjNzY4ZGVlYzJkYTFjN2E0ZDEzYzQxMzI1MDM2NGE3YWUwNjhmMTkzMDY0OGRjZDAxOThkNzM4NjZlNGRhY2Q3ZjliMzk2YTdmYTY2MGQxZWYxNGFhM2M2YTdkNWFkZTJhNmI4MDc1YjU2NDBlYWQ3ZTZhODdmOGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
