# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODVmNzA0MzdkYmY5YzE2N2Q3N2UzNjY2MDlhODBkYjcxOWM1OWVkYWZiN2U3YzUzOTU0ODkzNTg4MWFhYTk3ZGM0NmYzOTMzNDQ5MjhhNGIzNWRiZTIzNDE1ZDM5MzUwMThjMjM4NTgxNDdlYmRmMDIyMjU3ODdhZmI2ODk1ZjI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
