# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjJiYjhhNjE5MDJiOTcxYThhODQwMTIyZWVkOTdhZTU5MWNmZjBkZDIyOThiNzE4ZDQ2M2JkZWY1ZWY3NWEyYjg3ZTRkODFmNWVjNDQ4YmM4M2VjODIzNmI1MDBkNGNiMjM1YTYzZDNkMDZmOWU4YWNlYTE3OTg1ZTVkOGQ0ZmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
