# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjdjY2RjNzVjNDNhYzdkNmNkOThjNTUyZmE0MDRmMzYyMTgxMDhiYjcwYzY0NWYzYjRjNTRlN2JkNTE2ODY1Y2I0NzI2NzkxNmM5MDIzYjRhODU3ODNmY2U4YmY5NzI1ZGI3ZGQwYWZjMGM3NzVlYjcyNGFmYzJkMDU0YjQwNmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
