package com.saathratri.developer.blog.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TajUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserAllPropertiesEquals(TajUser expected, TajUser actual) {
        assertTajUserAutoGeneratedPropertiesEquals(expected, actual);
        assertTajUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserAllUpdatablePropertiesEquals(TajUser expected, TajUser actual) {
        assertTajUserUpdatableFieldsEquals(expected, actual);
        assertTajUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserAutoGeneratedPropertiesEquals(TajUser expected, TajUser actual) {
        assertThat(actual)
            .as("Verify TajUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserUpdatableFieldsEquals(TajUser expected, TajUser actual) {
        assertThat(actual)
            .as("Verify TajUser relevant properties")
            .satisfies(a -> assertThat(a.getLogin()).as("check login").isEqualTo(expected.getLogin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTajUserUpdatableRelationshipsEquals(TajUser expected, TajUser actual) {
        // empty method
    }
}
