# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODE2OGNjNjRlMjZhMjhlNjg0YmU1ZDE1YmE0NTdmY2Q0YjUwODFjOWU3N2QwOTQ4MjM3NTY5YjQ5MjM2YWE3ZGExZjgwMjZkNGNjOGVjOTNiNmJkY2NkZGY1YzE5MDc1ODUyY2RkNGJhZWY5YmY0NGM2OGZiOGY2ODA5NDllNGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
