# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjRkMjA1ODA2NWMyZmFhZDdjZmM5Y2NlNmFiYzExZGQzOTJkMzJiMjFlMjRjM2UxYzdhZDhjNmVlNDA2YzdjMmFhYmNiMGMwNzBkZDU1YjlhMGEyZThlMjk4YTM3N2E0MTAwM2U3YjNkM2QwNmYyOWIxYjY1OGE5MTc5OWUxODI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
