# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmE3YzU0OWNhYWVmMThiMWQ2ZmYwYzFjMTM1NzliNTViODVjMjAzMDNlMDU4ODBhNjQ2OGVmMGJhYWMxYTZmZGY1N2FhOTcyNDQ4NDQ4NWMxODNjOGZiOTdmMzAyMjc2YWNhNDk1ZjZmNGM3NmJlNTVhYjkwZDJjNjJlNzZjZmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
